### ISSUE TITLE
7.2.1 bad link

### ISSUE THREAD

**Issue by jsaligoe** [INSPIRE-MIF/gp-ogc-api-features#19]
7.2.1 "OAPIF-core" link  http://www.opengis.net/spec/ogcapi-features-1/1.0/req/core returns "not found"

**Comment by cportele** [comment]
The opengis.net/spec URIs are mainly identifiers for elements in OGC specifications (see [this OGC policy document](http://portal.opengeospatial.org/files/?artifact_id=39194)), not URLs. 

That said, since OGC has now moved from PDF to HTML to publish their standards, the spec URIs can be mapped to anchors in the specification document and soon all the spec URIs of the standard should de-reference. This one, for example, to http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#rc_core.
