### ISSUE TITLE
Encoding for time series data

### ISSUE THREAD

**Issue by tervo** [INSPIRE-MIF/gp-ogc-api-features#53]
Currently recommendation `/rec/geojson/geojson-inspire` recommends GeoJSON as encoding. Pure GeoJSON does not, however, work well for time series data. Alternative encoding proposal is defined in OGC [OMSF-profile ](https://github.com/opengeospatial/omsf-profile) and discussed in https://ies-svn.jrc.ec.europa.eu/projects/2017-2/wiki

The O&M guideline is currently under review in OGC. Proposed OMSF-profile is most probably not the final version but it's still a good baseline for time series data. Can we already propose that as encoding for time series data as pure GeoJSON is  not feasible?

**Comment by cportele** [comment]
I do not think this is necessary:

* Following the INSPIRE-GeoJSON-encoding rule is just a recommendation, so there is no conformance issue, if one deviates from the encoding rule. We do that, too. I plan to document the reasons in the deployment issues. Since the [JSON variant of OMSF](https://github.com/opengeospatial/omsf-profile/tree/master/omsf-json) is a GeoJSON profile, an API that uses OMSF-GeoJSON would still conform to the "INSPIRE-OAPIF-GeoJSON" requirements class.
* OMSF is a good starting point, but maybe there has not been enough discussion/review/uptake to explicitly recommend it at this point?

**Comment by alexanderkotsev** [comment]
I agree with @cportele that we probably do not need that at least at this stage. In addition to what is already said, there is work ongoing for proposing a good practice on [SensorThings API](https://www.ogc.org/standards/sensorthings) as an INSPIRE Download service. The default encoding is JSON, but there is discussion on also having a GeoJSON encoding for SensorThings. See this [GitHub issue](https://github.com/opengeospatial/sensorthings/issues/70). This approach would provide an approach which is dedicated explicitly to time series.

**Comment by sgrellet** [comment]
I agree with both @alexanderkotsev and @cportele. Indeed we work hard on having SensorThings API as a good practice for INSPIRE download service.
In addition, with regards to GeoJSON as a resultFormat, it's more than a discussion there are already implementations work going on : see https://github.com/opengeospatial/sensorthings/issues/70

**Comment by alexanderkotsev** [comment]
The proposed line of action of the sub-group is to discuss this issue at the forthcoming MIG and MIG-T meetings and also for the communities dealing with multidimensional data structures to consider the possibility to create a INSPIRE good practice that can handle generation of feature data on demand through e.g. the OGC Environmental Data Retrieval API.
