### ISSUE TITLE
How to deal with 406 Not Acceptable error reports?

### ISSUE THREAD

**Issue by michellutz** [INSPIRE-MIF/gp-ogc-api-features#7]
Would the approach discussed in https://github.com/opengeospatial/oapi_common/issues/75 be a good way of dealing with errors (incl. INSPIRE-specific ones)?

**Comment by cportele** [comment]
Since OGC API Feature Core does not require this or any other specific response content for 4xx/5xx codes, this should not become a requirement in INSPIRE, if it is the goal to support off-the-shelf software implementing the standard.

This could change, if there would be a standard extension that prescribes the content of such responses and that is widely implemented.

In general clients need to be prepared anyhow to receive responses that are not generated by the API, but by some other component in the network (e.g. 502, 503, 504).

**Comment by jsaligoe** [comment]
@cportele Agreed.  Let's be pragmatic in our approach and enable commercial and open source software providers to implement OGC API Features core without concern that the initial implementations will fail INSPIRE requirements.
