### ISSUE TITLE
What are the recommended link parameters for the GeoJSON encoding rule?

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/gp-ogc-api-features#87]
Hi,

I have a question about the following recommendation:

> The GeoJSON encoding rule used for each feature collection and the features it contains SHOULD be documented in accordance with the guidelines in the [repository for alternative encodings](https://github.com/INSPIRE-MIF/2017.2) and SHOULD be based on model transformations and conversion rules documented in that repository if the feature collection provides data that are harmonised according to the [[IRs for ISDSS](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231&from=EN)].

I would like to add a link to the alternative encoding rule used in an OGC API Features service. What are the recommended link parameters?

**Comment by heidivanparys** [comment]
That should be documented in the metadata, see

- https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02010R1089-20141231#tocId15
- https://github.com/INSPIRE-MIF/technical-guidelines/blob/2023.1/metadata/metadata-iso19139/metadata-iso19139.adoc#annex-b-mapping-of-iso-191152003-core-elements-and-inspire-implementing-rules-for-metadata-informative
- https://github.com/INSPIRE-MIF/technical-guidelines/blob/2023.1/metadata/metadata-iso19139/metadata-iso19139.adoc#3231-data-encoding

A related issue is https://github.com/INSPIRE-MIF/gp-geopackage-encodings/issues/25.

**Comment by Kate-Lyndegaard** [comment]
Dear @heidivanparys ,

Thank you very much for the clarification.

Kind regards,
Kate

**Comment by PB-GNM** [comment]
If an OGC-API-Features service provider has no access to the metadata of the dataset, it should be possible to add a link to the description of the encoding, especially when the output encoding is different from the original dataset encoding. Therefor in the open tender for OGC-API-Features according to OGC, Dutch ADR and  INSPIRE we assumed a link was needed.
The tender resulted in 3 different implementations, because it is not prescribed how it should be done at https://github.com/INSPIRE-MIF/gp-ogc-api-features/blob/master/spec/oapif-inspire-download.md#83-requirements-class-inspire-oapif-geojson-: 
[Deegree](https://test.haleconnect.de/ogcapi/datasets/simplified-addresses/v1):             {"href":https://github.com/INSPIRE-MIF/2017.2/tree/master/GeoJSON/ads,"rel":"describedby","type":"text/html","title":"Encoding description"} at /collections level
[Pygeoapi](https://apitestbed.geonovum.nl/adr_pygeoapi/v1):           {"href":https://github.com/INSPIRE-MIF/2017.2/tree/master/GeoJSON/ads,"rel":"about","type":"text/html","title":"Description of the encoding","hreflang":"en"} at /collections/Addresses level
[Geoserver](https://geonovum.geosolutionsgroup.com/geoserver/inspire/ogc/features/v1):         {"href":https://github.com/INSPIRE-MIF/2017.2/blob/master/GeoJSON/ads/simple-addresses.md,"rel":"describedBy","type":"text/html","title":"GeoJSON Encoding Rule for INSPIRE Addresses"} at /collections/AddressesNL level

Could this be a reason for reopening this call and changing https://github.com/INSPIRE-MIF/gp-ogc-api-features/blob/master/spec/oapif-inspire-download.md on this point?

Maybe a recommendation could be added to put it in the metadata of the dataset, but a link at /collection or /collection/{collection-ID} for the case a server provider has no access to the metadata of the dataset.
